Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8081, guest: 80
  config.vm.synced_folder "../app", "/var/www/application"
  config.vm.synced_folder "ext", "/usr/lib/php5/20121212+lfs/ext"
  config.vm.synced_folder "php", "/etc/php5"
end