Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host: 8081, guest: 80
  config.vm.synced_folder "../app", "/var/www/application",
  owner: "www-data",
      mount_options: ["dmode=755,fmode=755"]
  config.vm.synced_folder "ext", "/usr/lib/php5/20121212+lfs/ext",
  owner: "www-data",
      mount_options: ["dmode=755,fmode=755"]
  config.vm.synced_folder "php", "/etc/php5",
  owner: "www-data",
      mount_options: ["dmode=755,fmode=755"]
end