test: 
    pattern: /test/{hey}
    controller: testController
    action: test
    srcFolder: test
    security: false	
test1:
    pattern: /test1
    controller: test1Controller
    action: test1
    srcFolder: test
    security: false
test2:
    pattern: /test2
    controller: test2Controller
    action: test2
    srcFolder: test
    security: false
longpoll:
    pattern: /longpoll
    controller: longPollController
    action: longpoll
    srcFolder: test
    security: false
testLongpoll:
    pattern: /testlongpoll
    controller: testLongPollController
    action: testlongpoll
    srcFolder: test
    security: false
dragdropfileuploadBackend:
    pattern: /fileupload
    controller: DragDropFileUploadController
    action: upload
    srcFolder: test
    security: false
dragdropfileuploadFrontEnd:
    pattern: /fileupload/dragdrop
    controller: DragDropFileUploadFrontEndController
    action: view
    srcFolder: test
    security: false
scrollBottom:
    pattern: /scrollBottom
    controller: scrollBottomController
    action: view
    srcFolder: test
    security: false
setVariable:
    pattern: /setVariable
    controller: setVariableController
    action: view
    srcFolder: usability
    security: false
import:
    pattern: /import
    controller: importController
    action: view
    srcFolder: usability
    security: false
include:
    pattern: /include
    controller: includeController
    action: view
    srcFolder: usability
    security: false
for:
    pattern: /for
    controller: forController
    action: view
    srcFolder: usability
    security: false
block:
    pattern: /block
    controller: blockController
    action: view
    srcFolder: usability
    security: false
use:
    pattern: /use
    controller: useController
    action: view
    srcFolder: usability
    security: false
translation:
    pattern: /translation
    controller: translationController
    action: view
    srcFolder: usability
    security: false
404:
    template: 404.html
404:
    controller: notFoundController
    action: view
    srcFolder: usability
    security: false
patternVariable:
    pattern: /patternVariable/{variable}
    controller:  patternVariableController
    action: view
    srcFolder: usability
    security: false
db:
    pattern: /db/{entryMsg}
    controller:  dbController
    action: view
    srcFolder: usability
    security: false
http:
    pattern: /http
    controller:  httpController
    action: view
    srcFolder: usability
    security: false
render:
    pattern: /render
    controller:  renderController
    action: view
    srcFolder: usability
    security: false
JsonResponse:
    pattern: /JsonResponse
    controller:  JsonResponseController
    action: view
    srcFolder: usability
    security: false
authentification:
    pattern: /authentification
    controller:  authentificationController
    action: view
    srcFolder: usability
    security: false