root:
    pattern: /
    controller: menuController
    action: view
    srcFolder: usability
    security: false
menu:
    pattern: /menu
    controller: menuController
    action: view
    srcFolder: usability
    security: false
setVariable:
    pattern: /setVariable
    controller: setVariableController
    action: view
    srcFolder: usability
    security: false
import:
    pattern: /import
    controller: importController
    action: view
    srcFolder: usability
    security: false
include:
    pattern: /include
    controller: includeController
    action: view
    srcFolder: usability
    security: false
for:
    pattern: /for
    controller: forController
    action: view
    srcFolder: usability
    security: false
block:
    pattern: /block
    controller: blockController
    action: view
    srcFolder: usability
    security: false
use:
    pattern: /use
    controller: useController
    action: view
    srcFolder: usability
    security: false
translation:
    pattern: /translation
    controller: translationController
    action: view
    srcFolder: usability
    security: false
404:
    template: 404.html
404:
    controller: notFoundController
    action: view
    srcFolder: usability
    security: false
patternVariable:
    pattern: /patternVariable/{variable}
    controller:  patternVariableController
    action: view
    srcFolder: usability
    security: false
db:
    pattern: /db/{entryMsg}
    controller:  dbController
    action: view
    srcFolder: usability
    security: false
http:
    pattern: /http
    controller:  httpController
    action: view
    srcFolder: usability
    security: false
render:
    pattern: /render
    controller:  renderController
    action: view
    srcFolder: usability
    security: false
JsonResponse:
    pattern: /JsonResponse
    controller:  JsonResponseController
    action: view
    srcFolder: usability
    security: false
validation:
    pattern: /validation
    controller:  validationController
    action: view
    srcFolder: usability
    security: false
    ajax: true
validationTest:
    pattern: /validationTest
    controller:  validationTestController
    action: view
    srcFolder: usability
    security: false
authentication:
    pattern: /authentication
    controller:  authenticationController
    action: view
    srcFolder: usability
    security: false
safesite:
    pattern: /safesite
    controller:  safesiteController
    action: view
    srcFolder: usability
    security: true
logout:
    pattern: /logout
    controller:  logoutController
    action: view
    srcFolder: usability
    security: true
fileUpload:
    pattern: /fileUpload
    controller:  FileUploadController
    action: upload
    srcFolder: usability
    security: false
fillElement:
    pattern: /fillElement
    controller:  fillElementController
    action: view
    srcFolder: usability
    security: false
longpolling:
    pattern: /longpolling
    controller:  longPollController
    action: longpoll
    srcFolder: usability
    security: false
poll:
    pattern: /poll
    controller:  testPollController
    action: view
    srcFolder: usability
    security: false
scrollBottom:
    pattern: /scrollBottom
    controller: scrollBottomController
    action: view
    srcFolder: usability
    security: false
datetime:
    pattern: /datetime
    controller: dateTimeController
    action: view
    srcFolder: usability
    security: false
fbLogin:
    pattern: /fblogin
    controller: fbLoginController
    action: login
    srcFolder: usability
    security: false