test: 
    pattern: /test/{hey}
    controller: testController
    action: test
    srcFolder: test
    security: false	
test1:
    pattern: /test1
    controller: test1Controller
    action: test1
    srcFolder: test
    security: false
404:
    controller: test1Controller
    action: test1
    srcFolder: test
    security: false
404:
    template: 404.html